name: Unity Build Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.unity
          key: UnityCache

      - name: Unity - Build Windows
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: 2022.3.0f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: WindowsBuild
          path: build/StandaloneWindows64/

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.unity
          key: UnityCache

      - name: Unity - Build Android
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
          unityVersion: 2022.3.0f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Android Build
        uses: actions/upload-artifact@v3
        with:
          name: AndroidBuild
          path: build/Android/
